# Find optimal rotation matrix to reduce to a minimum variance of coordinates on the z-axis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_pos = pd.read_csv('position_joints.trc', delimiter='\t', skiprows=3)
head_pose = np.array(data_pos.loc[275:, ["X15", "Y15", "Z15"]])
feet_pose = np.array(data_pos.loc[275:, ["X5", "Y5", "Z5"]])

In [3]:
head_pose.shape

start_head_pose = head_pose[0]

In [7]:
def cost(rot_coefs):
    # The cost is the absolute mean z-coordinate of the head
    rot_mat = np.array([rot_coefs[0:3], rot_coefs[3:6], rot_coefs[6:9]])
    rotated_head = head_pose@rot_mat
    rotated_feet = feet_pose@rot_mat
    cost = np.max(rotated_head[:, 2] - 1.5)**2
    cost += np.max(rotated_feet[:, 2])**2
    return cost

In [8]:
from scipy.optimize import fmin_bfgs

rot_0 = [1, 0, 0, 0, 1, 0, 0, 0, 1]
rot_opt = fmin_bfgs(cost, rot_0)

print(rot_opt)
print(cost(rot_opt))
print(np.array([rot_opt[0:3], rot_opt[3:6], rot_opt[6:9]]))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 8
         Function evaluations: 100
         Gradient evaluations: 10
[1.         0.         0.07116417 0.         1.         0.72475652
 0.         0.         0.00308123]
7.315743882345976e-14
[[1.         0.         0.07116417]
 [0.         1.         0.72475652]
 [0.         0.         0.00308123]]


In [9]:
print(head_pose@(np.array([rot_opt[0:3], rot_opt[3:6], rot_opt[6:9]])))

[[6.477442   1.4379753  1.49999975]
 [6.4552985  1.4150096  1.48176521]
 [6.4465084  1.4050653  1.47390964]
 [6.4499093  1.4077205  1.47606087]
 [6.450994   1.4090566  1.47711172]
 [6.4407118  1.4002333  1.47001399]
 [6.4211402  1.3831517  1.45628743]
 [6.3990921  1.3635915  1.44058479]
 [6.3818241  1.3472601  1.42753128]
 [6.3722427  1.3368705  1.41929915]
 [6.3661234  1.3299146  1.41380271]
 [6.3564549  1.3208832  1.4065751 ]
 [6.3379932  1.3043442  1.3932971 ]
 [6.3107419  1.2795043  1.37337638]
 [6.2821512  1.253254   1.35233228]
 [6.2599652  1.2326667  1.33583848]
 [6.2433454  1.2166757  1.32305875]
 [6.2277113  1.2018105  1.31116723]
 [6.2123053  1.1891418  1.30091584]
 [6.1956876  1.1775426  1.29138696]
 [6.1735037  1.1603421  1.27739089]
 [6.1465275  1.13625    1.25801497]
 [6.1212285  1.1127568  1.2391749 ]
 [6.1024323  1.0967945  1.22628048]
 [6.0910333  1.0892377  1.22003194]
 [6.082186   1.0835105  1.21528348]
 [6.067085   1.0701386  1.20451542]
 [6.0444216  1.048848   1.18