# Find optimal rotation matrix to reduce to a minimum variance of coordinates on the z-axis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_pos = pd.read_csv('position_joints.trc', delimiter='\t', skiprows=3)
head_pose = np.array(data_pos.loc[275:, ["X15", "Y15", "Z15"]])
feet_pose = np.array(data_pos.loc[275:, ["X5", "Y5", "Z5"]])

In [3]:
head_pose.shape

start_head_pose = head_pose[0]

In [4]:
def cost(rot_coefs):
    # The cost is the absolute mean z-coordinate of the head
    rot_mat = np.array([rot_coefs[0:3], rot_coefs[3:6], rot_coefs[6:9]])
    rotated_head = head_pose@rot_mat
    rotated_feet = feet_pose@rot_mat
    cost = np.mean(rotated_head[:, 2] - 1.5)**2
    cost += np.mean(rotated_feet[:, 2])**2
    return cost

In [5]:
from scipy.optimize import fmin_bfgs

rot_0 = [1, 0, 0, 0, 1, 0, 0, 0, 1]
rot_opt = fmin_bfgs(cost, rot_0)

print(rot_opt)
print(cost(rot_opt))
print(np.array([rot_opt[0:3], rot_opt[3:6], rot_opt[6:9]]))

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 2
         Function evaluations: 50
         Gradient evaluations: 5
[1.         0.         0.31538233 0.         1.         0.75265143
 0.         0.         0.77584002]
7.534496838684299e-16
[[1.         0.         0.31538233]
 [0.         1.         0.75265143]
 [0.         0.         0.77584002]]


In [6]:
print(head_pose@(np.array([rot_opt[0:3], rot_opt[3:6], rot_opt[6:9]])))

[[6.477442   1.4379753  2.33352109]
 [6.4552985  1.4150096  2.30568091]
 [6.4465084  1.4050653  2.28967689]
 [6.4499093  1.4077205  2.28892798]
 [6.450994   1.4090566  2.291612  ]
 [6.4407118  1.4002333  2.28896434]
 [6.4211402  1.3831517  2.28157888]
 [6.3990921  1.3635915  2.27067335]
 [6.3818241  1.3472601  2.25586729]
 [6.3722427  1.3368705  2.23990318]
 [6.3661234  1.3299146  2.22779347]
 [6.3564549  1.3208832  2.21946106]
 [6.3379932  1.3043442  2.20686961]
 [6.3107419  1.2795043  2.18498623]
 [6.2821512  1.253254   2.160142  ]
 [6.2599652  1.2326667  2.13911915]
 [6.2433454  1.2166757  2.11997346]
 [6.2277113  1.2018105  2.10252634]
 [6.2123053  1.1891418  2.094852  ]
 [6.1956876  1.1775426  2.09606457]
 [6.1735037  1.1603421  2.08840939]
 [6.1465275  1.13625    2.0629579 ]
 [6.1212285  1.1127568  2.03406564]
 [6.1024323  1.0967945  2.01913875]
 [6.0910333  1.0892377  2.0198014 ]
 [6.082186   1.0835105  2.02075228]
 [6.067085   1.0701386  2.00541373]
 [6.0444216  1.048848   1.97